# Generated by Django 4.1.7 on 2023-03-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(max_length=256)),
                ('shorten_url', models.CharField(max_length=8)),
                ('creation_date', models.CharField(max_length=10)),
            ],
        ),
    ]
