# Generated by Django 4.1.1 on 2023-06-25 01:03

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(default=sqlalchemy.sql.expression.null, max_length=20)),
                ('rounds', models.IntegerField(default=0)),
                ('round', models.IntegerField(default=0)),
                ('connectedUsers', models.IntegerField(default=0)),
                ('started', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('uniqueUID', models.CharField(max_length=20)),
                ('roomName', models.CharField(max_length=20)),
                ('userScore', models.IntegerField(default=0)),
                ('channelsRoomName', models.CharField(max_length=100)),
                ('userColor', models.CharField(max_length=7)),
                ('isKing', models.IntegerField(default=0)),
            ],
        ),
    ]
